### ISSUE TITLE
Hello there.

### ISSUE THREAD

**Issue by keitheous** [pukei/scorm_rte#2]
As I was testing out this gem, i called the controller helper assign_sco_instance_id(sco_instance_id) without passing the sco_instance_id param - just to test if I have integrated it right. 

The good news is I am, Bad news is there is a spelling mistake in your validation error message.

**ScormRte::NoScoInstanceIdError: Always provide a unique SCO intance ID**

Tried looking for it in your directory but I couldn't locate it. Sorry still very new to rails.
Here's the screenshot. Thank you for this gem!

<img width="501" alt="screen shot 2017-12-07 at 10 40 30 am" src="https://user-images.githubusercontent.com/17760485/33691245-77930ebe-db3b-11e7-9df6-d482dffb644f.png">

**Comment by keitheous** [comment]
Hi I just noticed this

https://github.com/pukei/scorm_rte/commit/b9512c97eec8f404997770de43ef31d7b9896e25#diff-56165306fd1a9053fb30624fff70ae18

**Comment by paresharma** [comment]
Glad you could find some use for this.
My apologies for the delay in reply, I've fixed the typo anyway :)
