### ISSUE TITLE
Library not usable

### ISSUE THREAD

**Issue by ChiangChu** [pukei/scorm_rte#4]
When I try to import your gem I get the following error.
Fetching git@github.com:pukei/scrom-rte.git
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?

When I say 'yes' I get an git clone error, that I should check if I have the rights.

When I try to import the gem without the git information. Then it do work but I can't start the server because it is not rails 5 compatible.

Like this the library is at its current state not usable.

Would be nice if you could fix this.

**Comment by paresharma** [comment]
@ChiangChu 
My apologies but it's been a long time that worked on anything related to SCORM, but I tried creating a new Rails app, add the gem (the master branch) and followed the steps in the Readme, I was able to get the app up and running. So, at-least the gem works as it's suppose to.

I updated the Readme a bit hope that helps especially the part where you were suppose to use https endpoint for bundling with git.

If you still have any issues, I guess you can pastes a few logs or snapshot and I can help debug.

**Comment by ChiangChu** [comment]
Thx for updating the link that seems to have fixed the problem I could now download the gem without a problem.
